language: node_js
node_js:
  - "9"

cache: ~/.npm

install:
  - npm install

branches:
  only:
    - master

stages:
  - lint
  - test
  - coverage

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test
    - stage: coverage
      script: npm run coverage
