language: node_js
node_js:
  - "9"

cache: ~/.npm

install:
  - npm install

branches:
  only:
    - master

stages:
  - lint
  - test
  - coverage
  - deploy doc site
  - release

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test
    - stage: coverage
      script: npm run coverage
    - stage: deploy doc site
      script: npm run build:doc && touch ./docs/.nojekyll
      if: type != pull_request
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          local-dir: ./docs
    - stage: release
      if: type != pull_request
      script: npm run build && npx semantic-release
